apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-svc
  labels:
    app: {{ include "myapp.name" . }}
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
