replicaCount: 2

image:
  repository: wavecloud/nginx-oc
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: www.wavecloud.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            servicePort: 8081
  tls: []
